#' Simulated Multi-Strategy Cost-Utility Dataset with Discounted Costs
#'
#' A simulated individual-level dataset designed to illustrate multi-strategy
#' cost-utility and cost-effectiveness analyses under a discounted cost
#' scenario using the CEAgroupR package. This dataset mirrors the structure of
#' \code{cua_multi}, but applies a uniform annual discount rate to cost outcomes.
#'
#' All data contained in this dataset are fully synthetic and generated solely
#' for illustrative and methodological purposes. Variable distributions were
#' chosen to approximate plausible population-level prevalences in Spain
#' (e.g. diabetes and hypertension), but do not correspond to real individuals
#' or official microdata.
#'
#' @format
#' A data frame with 800 rows and the following variables:
#' \describe{
#'   \item{id}{Individual identifier.}
#'   \item{group}{Strategy group indicator (e.g. \code{"usual_care"},
#'     \code{"intervention_A"}, \code{"intervention_B"}).}
#'   \item{sex}{Sex of the individual (\code{"female"}, \code{"male"}).}
#'   \item{location}{Area of residence (\code{"urban"}, \code{"rural"}).}
#'   \item{diabetes}{Diabetes status (\code{"yes"}, \code{"no"}).}
#'   \item{HTA}{Hypertension status (\code{"yes"}, \code{"no"}).}
#'   \item{n_comorbidities}{Number of comorbid conditions.}
#'   \item{cost_total}{Total cost per individual after applying a 3\%
#'     annual discount rate.}
#'   \item{effect}{Effectiveness outcome (e.g. QALYs), unchanged relative to
#'     \code{cua_multi}.}
#' }
#'
#' @details
#' This dataset represents the same population and strategy set as
#' \code{cua_multi}, but with costs discounted at a constant annual rate
#' (3\%). It is intended to illustrate scenario-based analyses and discounted
#' cost evaluations in multi-strategy decision problems.
#'
#' @source
#' Simulated data generated by the package authors for illustrative purposes.
#'
#' @examples
#' ## Compare undiscounted and discounted multi-strategy costs
#' summary(cua_multi$cost_total)
#' summary(cua_multi_discounted$cost_total)
#'
#' @keywords datasets
"cua_multi_discounted"
