#' Simulated Multi-Strategy Cost-Utility Dataset
#'
#' A simulated individual-level dataset designed to illustrate cost-utility
#' and cost-effectiveness analyses involving multiple competing strategies
#' using the CEAgroupR package. This dataset represents a single analytical
#' scenario with more than two intervention alternatives, reflecting typical
#' multi-strategy decision problems in health economic evaluation.
#'
#' All data contained in this dataset are fully synthetic and generated solely
#' for illustrative and methodological purposes. Variable distributions were
#' chosen to approximate plausible population-level prevalences in Spain
#' (e.g. diabetes and hypertension), but do not correspond to real individuals
#' or official microdata.
#'
#' @format
#' A data frame with 800 rows and the following variables:
#' \describe{
#'   \item{id}{Individual identifier.}
#'   \item{group}{Strategy group indicator (e.g. \code{"usual_care"},
#'     \code{"intervention_A"}, \code{"intervention_B"}).}
#'   \item{sex}{Sex of the individual (\code{"female"}, \code{"male"}).}
#'   \item{location}{Area of residence (\code{"urban"}, \code{"rural"}).}
#'   \item{diabetes}{Diabetes status (\code{"yes"}, \code{"no"}).}
#'   \item{HTA}{Hypertension status (\code{"yes"}, \code{"no"}).}
#'   \item{n_comorbidities}{Number of comorbid conditions.}
#'   \item{cost_total}{Total cost per individual.}
#'   \item{effect}{Effectiveness outcome (e.g. QALYs).}
#' }
#'
#' @details
#' This dataset extends the structure of \code{cua_base} to a multi-strategy
#' setting. It is intended to demonstrate incremental cost-effectiveness
#' analysis involving more than two alternatives, including the construction
#' of cost-effectiveness planes, acceptability curves and value-of-information
#' analyses.
#'
#' @source
#' Simulated data generated by the package authors for illustrative purposes.
#'
#' @examples
#' ## Inspect strategy distribution
#' table(cua_multi$group)
#'
#' ## Multi-strategy cost-effectiveness analysis
#' res <- compute_icers(
#'   data      = cua_multi,
#'   group     = "group",
#'   cost      = "cost_total",
#'   effect    = "effect",
#'   ref_group = "usual_care",
#'   R         = 50,
#'   seed      = 123
#' )
#'
#' @keywords datasets
"cua_multi"
