#' Simulated Single-Scenario Cost-Utility Dataset with Discounted Costs
#'
#' A simulated individual-level dataset designed to illustrate cost-utility
#' and cost-effectiveness analyses under a discounted cost scenario using the
#' CEAgroupR package. This dataset mirrors the structure of \code{cua_base},
#' but applies a uniform annual discount rate to cost outcomes.
#'
#' All data contained in this dataset are fully synthetic and generated solely
#' for illustrative and methodological purposes. Variable distributions were
#' chosen to approximate plausible population-level prevalences in Spain
#' (e.g. diabetes and hypertension), but do not correspond to real individuals
#' or official microdata.
#'
#' @format
#' A data frame with 200 rows and the following variables:
#' \describe{
#'   \item{id}{Individual identifier.}
#'   \item{group}{Strategy group indicator (e.g. \code{"g0"}, \code{"g1"}).}
#'   \item{sex}{Sex of the individual (\code{"female"}, \code{"male"}).}
#'   \item{location}{Area of residence (\code{"urban"}, \code{"rural"}).}
#'   \item{diabetes}{Diabetes status (\code{"yes"}, \code{"no"}).}
#'   \item{HTA}{Hypertension status (\code{"yes"}, \code{"no"}).}
#'   \item{n_comorbidities}{Number of comorbid conditions.}
#'   \item{cost_total}{Total cost per individual after applying a 3\%
#'     annual discount rate.}
#'   \item{effect}{Effectiveness outcome (e.g. QALYs), unchanged relative to
#'     \code{cua_base}.}
#' }
#'
#' @details
#' This dataset represents the same underlying population and strategies as
#' \code{cua_base}, but with costs discounted at a constant annual rate
#' (3\%). It is intended to illustrate the handling of alternative analytical
#' scenarios within CEAgroupR, such as discounted versus undiscounted cost
#' analyses.
#'
#' @source
#' Simulated data generated by the package authors for illustrative purposes.
#'
#' @examples
#' ## Compare undiscounted and discounted costs
#' summary(cua_base$cost_total)
#' summary(cua_base_discounted$cost_total)
#'
#' @keywords datasets
"cua_base_discounted"
