#' Simulated Single-Scenario Cost-Utility Dataset
#'
#' A simulated individual-level dataset designed to illustrate basic
#' cost-utility and cost-effectiveness analyses using the CEAgroupR package.
#' The dataset represents a single analytical scenario with two alternative
#' strategies and includes demographic, clinical and economic variables
#' commonly used in health economic evaluations.
#'
#' All data contained in this dataset are fully synthetic and generated solely
#' for illustrative and methodological purposes. Variable distributions were
#' chosen to approximate plausible population-level prevalences in Spain
#' (e.g. diabetes and hypertension), but do not correspond to real individuals
#' or official microdata.
#'
#' @format
#' A data frame with 200 rows and the following variables:
#' \describe{
#'   \item{id}{Individual identifier.}
#'   \item{group}{Strategy group indicator (e.g. \code{"g0"}, \code{"g1"}).}
#'   \item{sex}{Sex of the individual (\code{"female"}, \code{"male"}).}
#'   \item{location}{Area of residence (\code{"urban"}, \code{"rural"}).}
#'   \item{diabetes}{Diabetes status (\code{"yes"}, \code{"no"}).}
#'   \item{HTA}{Hypertension status (\code{"yes"}, \code{"no"}).}
#'   \item{n_comorbidities}{Number of comorbid conditions.}
#'   \item{cost_total}{Total cost per individual.}
#'   \item{effect}{Effectiveness outcome (e.g. QALYs).}
#' }
#'
#' @details
#' This dataset is intended to serve as a minimal working example for
#' demonstrating the core analytical and graphical functionalities of
#' CEAgroupR, including incremental comparisons, bootstrap-based uncertainty
#' analysis and subgroup stratification.
#'
#' @source
#' Simulated data generated by the package authors for illustrative purposes.
#'
#' @examples
#' head(cua_base)
#'
#' @keywords datasets
"cua_base"
