#' Plot marginal distributions of incremental outcomes (Delta Cost or Delta Effect)
#'
#' This function visualizes marginal distributions of incremental costs
#' (`Delta_Cost`) or incremental effects (`Delta_Effect`) using bootstrap
#' replicates stored in a `cea_results_list` object generated by
#' `compute_icers()`. Supported geometries include histogram, density,
#' and boxplot. The function adheres to the unified graphical conventions
#' used across the package, including consistent mapping of aesthetics,
#' palette assignment, faceting rules, and tidy-style filtering.
#'
#' Colour aesthetics always reflect the primary comparison grouping, while
#' fill aesthetics reuse the same palette with controlled transparency.
#' Multiple datasets are represented using linetype patterns; a generator
#' ensures valid patterns regardless of the number of datasets.
#'
#' @inheritParams plot.icers
#' @param variable Character string. `"cost"` selects `Delta_Cost`,
#'   `"effect"` selects `Delta_Effect`.
#' @param geom_type Character string: `"histogram"`, `"density"`, or `"boxplot"`.
#' @param bins Integer. Number of bins when `geom_type = "histogram"`.
#'
#' @return A `ggplot` object.
#' @export
plot.marginals <- function(
    data,
    variable    = "cost",
    geom_type   = "histogram",
    color_by    = NULL,
    shape_by    = NULL,
    facet_by    = NULL,
    mode        = "Overall",
    filter_expr = NULL,
    facet_scales = "fixed",
    palette     = NULL,
    bins        = 30,
    ...
) {

  `%||%` <- function(a, b) if (!is.null(a)) a else b
  adjust_alpha <- function(cols, alpha = 0.5) scales::alpha(cols, alpha)

  # Unlimited linetype generator (valid for any length)
  generate_linetypes <- function(n) {
    base <- c(
      "11", "44", "13", "3311", "F2", "1248", "8899", "22FF",
      "4488", "F0F0", "1188", "3344", "77", "FF", "33CC", "6666"
    )
    rep(base, length.out = n)
  }

  # ============================================================
  # 1. Input extraction
  # ============================================================
  if (inherits(data, "cea_results_list")) {
    if (is.null(data$combined_replicates))
      stop("'combined_replicates' not found. Run compute_icers().")
    df <- data$combined_replicates
  } else if (inherits(data, "data.frame")) {
    df <- data
  } else {
    stop("Input must be a `cea_results_list` or a data frame.")
  }

  if (!"group_uid" %in% names(df)) {
    df$group_uid <- with(
      df,
      paste(dataset, subgroup_var, subgroup_level, comparison, sep = "_")
    )
  }

  # ============================================================
  # 2. Filtering
  # ============================================================
  if (!is.null(filter_expr)) {
    expr <- rlang::parse_expr(filter_expr)
    df <- dplyr::filter(df, !!expr)
  }

  # ============================================================
  # 3. Mode filtering
  # ============================================================
  mode <- match.arg(mode, c("Overall", "Subgroups"))
  if (mode == "Overall") {
    df <- df[df$subgroup_var == "Overall" | is.na(df$subgroup_var), ]
  } else {
    df <- df[df$subgroup_var != "Overall" & !is.na(df$subgroup_var), ]
  }

  # ============================================================
  # 4. Delta variable selection
  # ============================================================
  var_col <- switch(
    variable,
    "cost"   = "Delta_Cost",
    "effect" = "Delta_Effect",
    stop("`variable` must be 'cost' or 'effect'.")
  )

  # ============================================================
  # 5. Aesthetic defaults with user override
  # ============================================================
  default_color <- "comparison"
  default_shape <- "dataset"
  default_facet <- if (mode == "Subgroups") "subgroup" else "none"

  resolved_color <- color_by %||% default_color
  resolved_shape <- shape_by %||% default_shape
  resolved_facet <- facet_by %||% default_facet

  if (identical(color_by, "none"))  resolved_color <- NULL
  if (identical(shape_by, "none"))  resolved_shape <- NULL
  if (identical(facet_by, "none"))  resolved_facet <- NULL

  # ============================================================
  # 6. Base plot for theme/palette/facets
  # ============================================================
  base <- ce_plot_base(
    data         = df,
    color_by     = resolved_color,
    shape_by     = resolved_shape,
    facet_by     = resolved_facet,
    facet_scales = facet_scales,
    palette      = palette,
    auto_layout  = TRUE
  )

  p <- base$plot
  color_var      <- base$color_var
  shape_var      <- base$shape_var
  palette_values <- base$palette_values
  fill_palette   <- adjust_alpha(palette_values, alpha = 0.5)

  args      <- list(...)
  alpha_val <- args$alpha     %||% 0.5
  lw_val    <- args$linewidth %||% 0.6

  # ============================================================
  # 7. Unified scales (before geoms)
  # ============================================================
  if (!is.null(color_var)) {
    p <- p + ggplot2::scale_colour_manual(values = palette_values)
    p <- p + ggplot2::scale_fill_manual(values = fill_palette)
  }

  # Unlimited linetype scale for dataset
  if (!is.null(shape_var)) {
    lt_vals <- generate_linetypes(dplyr::n_distinct(df[[shape_var]]))
    names(lt_vals) <- sort(unique(df[[shape_var]]))
    p <- p + ggplot2::scale_linetype_manual(values = lt_vals)
  }

  # Hide irrelevant legends
  if (!is.null(color_var) &&
      dplyr::n_distinct(df[[color_var]]) == 1)
    p <- p + ggplot2::guides(colour = "none", fill = "none")

  if (!is.null(shape_var) &&
      dplyr::n_distinct(df[[shape_var]]) == 1)
    p <- p + ggplot2::guides(linetype = "none")

  # ============================================================
  # 8. GEOMETRIES
  # ============================================================

  # 8a. Density
  if (geom_type == "density") {

    aes_density <- ggplot2::aes(
      x     = .data[[var_col]],
      group = group_uid
    )

    if (!is.null(color_var)) {
      aes_density$colour <- rlang::sym(color_var)
      aes_density$fill   <- rlang::sym(color_var)
    }
    if (!is.null(shape_var))
      aes_density$linetype <- rlang::sym(shape_var)

    p <- p + ggplot2::geom_density(
      data        = df,
      mapping     = aes_density,
      alpha       = 0.5,
      linewidth   = lw_val,
      inherit.aes = FALSE
    )

    # Legend override (dataset)
    if (!is.null(shape_var) &&
        dplyr::n_distinct(df[[shape_var]]) > 1) {

      p <- p + ggplot2::guides(
        linetype = ggplot2::guide_legend(
          title = shape_var,
          override.aes = list(
            fill    = "grey85",
            colour  = "black",
            linetype = lt_vals,
            size    = 0.7
          )
        )
      )
    }

    # 8b. Histogram
  } else if (geom_type == "histogram") {

    aes_hist <- ggplot2::aes(
      x     = .data[[var_col]],
      group = group_uid
    )

    if (!is.null(color_var)) {
      aes_hist$fill   <- rlang::sym(color_var)
      aes_hist$colour <- rlang::sym(color_var)
    }
    if (!is.null(shape_var))
      aes_hist$linetype <- rlang::sym(shape_var)

    p <- p + ggplot2::geom_histogram(
      data        = df,
      mapping     = aes_hist,
      bins        = bins,
      alpha       = 0.5,
      linewidth   = lw_val,
      position    = "identity",
      inherit.aes = FALSE
    )

    # Legend override (dataset)
    if (!is.null(shape_var) &&
        dplyr::n_distinct(df[[shape_var]]) > 1) {

      p <- p + ggplot2::guides(
        linetype = ggplot2::guide_legend(
          title = shape_var,
          override.aes = list(
            fill    = "grey85",
            colour  = "black",
            linetype = lt_vals,
            size    = 0.7
          )
        )
      )
    }

    # 8c. Boxplot — independent canvas (avoids inherited aesthetics)
  } else if (geom_type == "boxplot") {

    x_var <- color_var
    if (is.null(x_var))
      stop("Boxplot requires a valid `color_by` aesthetic for x-axis categories.")

    p <- ggplot2::ggplot(
      df,
      ggplot2::aes(
        x = factor(.data[[x_var]], levels = unique(.data[[x_var]])),
        y = .data[[var_col]]
      )
    ) +
      ggplot2::geom_boxplot(
        ggplot2::aes(
          fill     = if (!is.null(color_var)) .data[[color_var]] else NULL,
          colour   = if (!is.null(color_var)) .data[[color_var]] else NULL,
          linetype = if (!is.null(shape_var)) .data[[shape_var]] else NULL
        ),
        alpha         = 0.4,
        linewidth     = lw_val,
        outlier.shape = 21,
        outlier.size  = 1.5
      ) +
      base$plot$theme

    if (!is.null(color_var)) {
      p <- p + ggplot2::scale_colour_manual(values = palette_values)
      p <- p + ggplot2::scale_fill_manual(values = fill_palette)
    }
    if (!is.null(shape_var))
      p <- p + ggplot2::scale_linetype_manual(values = lt_vals)

    # Legend override
    if (!is.null(shape_var) &&
        dplyr::n_distinct(df[[shape_var]]) > 1) {

      p <- p + ggplot2::guides(
        linetype = ggplot2::guide_legend(
          title = shape_var,
          override.aes = list(
            fill    = "grey85",
            colour  = "black",
            linetype = lt_vals,
            size    = 0.7
          )
        )
      )
    }

    p <- p +
      ggplot2::labs(
        title    = paste("Distribution of Delta", tools::toTitleCase(variable)),
        x        = x_var,
        y        = "Value",
        fill     = color_var,
        colour   = color_var,
        linetype = shape_var
      )

    return(p)

  } else {
    stop("`geom_type` must be 'histogram', 'density', or 'boxplot'.")
  }

  # ------------------------------------------------------------
  # 9. Axes and labels for histogram/density
  # ------------------------------------------------------------
  p <- p +
    ggplot2::scale_x_continuous(labels = scales::label_number()) +
    ggplot2::scale_y_continuous(labels = scales::label_number()) +
    ggplot2::labs(
      title    = paste("Distribution of Delta", tools::toTitleCase(variable)),
      x        = paste("Delta", tools::toTitleCase(variable)),
      y        = "Density",
      fill     = color_var,
      colour   = color_var,
      linetype = shape_var
    )

  return(p)
}
