#' Plot marginal distributions of incremental outcomes (Delta Cost or Delta Effect)
#'
#' This function visualizes marginal distributions of incremental costs
#' (`Delta_Cost`) or incremental effects (`Delta_Effect`) using bootstrap
#' replicates stored in a `cea_results_list` object generated by
#' `compute_icers()`. Supported geometries include histogram, density,
#' and boxplot. The function adheres to the unified graphical conventions
#' of the package, including consistent mappings, palette assignment,
#' faceting rules, and tidy-style filtering.
#'
#' Colour aesthetics always reflect the primary comparison grouping unless
#' overwritten by the user. Fill aesthetics reuse the same palette with
#' controlled transparency. Multiple datasets are represented using the
#' linetype patterns and point shapes generated internally by `ce_plot_base()`.
#'
#' When `shape_by = NULL` (or `"none"`), all shape/linetype-related aesthetics
#' are fully disabled: no linetype mapping, no shape mapping, and no linetype
#' legend entries are used in any geometry. Geometric outlines revert to
#' solid lines.
#'
#' @inheritParams plot.icers
#' @param variable Character string. `"cost"` selects `Delta_Cost`,
#'   `"effect"` selects `Delta_Effect`.
#' @param geom_type Character string: `"histogram"`, `"density"`, or `"boxplot"`.
#' @param bins Integer. Number of bins when `geom_type = "histogram"`.
#'
#' @return A `ggplot` object.
#' @export
plot.marginals <- function(
    data,
    variable    = "cost",
    geom_type   = "histogram",
    color_by    = NULL,
    shape_by    = NULL,
    facet_by    = NULL,
    mode        = "Overall",
    filter_expr = NULL,
    facet_scales = "fixed",
    palette     = NULL,
    bins        = 30,
    ...
) {

  `%||%` <- function(a, b) if (!is.null(a)) a else b
  alpha_fill <- function(cols) scales::alpha(cols, 0.5)

  # ============================================================
  # 1. Input extraction
  # ============================================================
  if (inherits(data, "cea_results_list")) {
    if (is.null(data$combined_replicates))
      stop("'combined_replicates' not found. Run compute_icers().")
    df <- data$combined_replicates
  } else if (inherits(data, "data.frame")) {
    df <- data
  } else stop("Input must be a `cea_results_list` or a data frame.")

  if (!"group_uid" %in% names(df)) {
    df$group_uid <- with(
      df,
      paste(dataset, subgroup_var, subgroup_level, comparison, sep = "_")
    )
  }

  # ============================================================
  # 2. Filtering
  # ============================================================
  if (!is.null(filter_expr)) {
    expr <- rlang::parse_expr(filter_expr)
    df <- dplyr::filter(df, !!expr)
  }

  # ============================================================
  # 3. Mode filtering
  # ============================================================
  mode <- match.arg(mode, c("Overall", "Subgroups"))
  if (mode == "Overall") {
    df <- df[df$subgroup_var == "Overall" | is.na(df$subgroup_var), ]
  } else {
    df <- df[df$subgroup_var != "Overall" & !is.na(df$subgroup_var), ]
  }

  # ============================================================
  # 4. Delta variable selection
  # ============================================================
  var_col <- switch(
    variable,
    "cost"   = "Delta_Cost",
    "effect" = "Delta_Effect",
    stop("`variable` must be 'cost' or 'effect'.")
  )

  # ============================================================
  # 5. Unified defaults
  # ============================================================
  default_color <- "comparison"
  default_shape <- "dataset"
  default_facet <- if (mode == "Subgroups") "subgroup" else "none"

  resolved_color <- color_by %||% default_color
  resolved_shape <- shape_by %||% default_shape
  resolved_facet <- facet_by %||% default_facet

  if (identical(color_by, "none"))  resolved_color <- NULL
  if (identical(shape_by, "none"))  resolved_shape <- NULL
  if (identical(facet_by, "none"))  resolved_facet <- NULL

  # ============================================================
  # 6. Base plot engine
  # ============================================================
  base <- ce_plot_base(
    data         = df,
    color_by     = resolved_color,
    shape_by     = resolved_shape,
    facet_by     = resolved_facet,
    facet_scales = facet_scales,
    palette      = palette
  )

  p <- base$plot
  color_var        <- base$color_var
  shape_var        <- base$shape_var          # may be NULL
  palette_values   <- base$palette_values
  fill_palette     <- alpha_fill(palette_values)

  # Only present if shape_by was active:
  linetype_values  <- base$linetype_values
  shape_values     <- base$shape_values

  args      <- list(...)
  alpha_val <- args$alpha     %||% 0.5
  lw_val    <- args$linewidth %||% 0.6

  # ============================================================
  # 7. Colour & fill scales
  # ============================================================
  if (!is.null(color_var)) {
    p <- p + ggplot2::scale_colour_manual(values = palette_values)
    p <- p + ggplot2::scale_fill_manual(values = fill_palette)
  }

  # ============================================================
  # 8. Shape/linetype scales ONLY IF shape_var is active
  # ============================================================
  if (!is.null(shape_var)) {
    p <- p + ggplot2::scale_linetype_manual(values = linetype_values)
    p <- p + ggplot2::scale_shape_manual(values = shape_values)
  } else {
    # Remove any linetype/shape legends
    p <- p + ggplot2::guides(linetype = "none", shape = "none")
  }

  # ============================================================
  # 9. GEOMETRIES
  # ============================================================

  # ---------- DENSITY ----------
  if (geom_type == "density") {

    aes_density <- ggplot2::aes(
      x     = .data[[var_col]],
      group = group_uid
    )

    if (!is.null(color_var)) {
      aes_density$colour <- rlang::sym(color_var)
      aes_density$fill   <- rlang::sym(color_var)
    }

    if (!is.null(shape_var)) {
      aes_density$linetype <- rlang::sym(shape_var)
    }

    p <- p + ggplot2::geom_density(
      data        = df,
      mapping     = aes_density,
      alpha       = 0.5,
      linewidth   = lw_val,
      inherit.aes = FALSE
    )

    # Dataset legend override only if shape_var active
    if (!is.null(shape_var) &&
        dplyr::n_distinct(df[[shape_var]]) > 1) {

      if (!is.null(color_var) && color_var == shape_var) {
        override_fill   <- fill_palette
        override_colour <- palette_values
      } else {
        override_fill   <- rep("grey85", length(linetype_values))
        override_colour <- rep("black",   length(linetype_values))
      }

      p <- p + ggplot2::guides(
        linetype = ggplot2::guide_legend(
          title        = shape_var,
          override.aes = list(
            fill     = override_fill,
            colour   = override_colour,
            linetype = linetype_values,
            size     = 0.7
          )
        )
      )
    }

    # ---------- HISTOGRAM ----------
  } else if (geom_type == "histogram") {

    aes_hist <- ggplot2::aes(
      x     = .data[[var_col]],
      group = group_uid
    )

    if (!is.null(color_var)) {
      aes_hist$fill   <- rlang::sym(color_var)
      aes_hist$colour <- rlang::sym(color_var)
    }

    if (!is.null(shape_var))
      aes_hist$linetype <- rlang::sym(shape_var)

    p <- p + ggplot2::geom_histogram(
      data        = df,
      mapping     = aes_hist,
      bins        = bins,
      alpha       = 0.5,
      linewidth   = lw_val,
      position    = "identity",
      inherit.aes = FALSE
    )

    # dataset legend override IF shape_by active
    if (!is.null(shape_var) &&
        dplyr::n_distinct(df[[shape_var]]) > 1) {

      if (!is.null(color_var) && color_var == shape_var) {
        override_fill   <- fill_palette
        override_colour <- palette_values
      } else {
        override_fill   <- rep("grey85", length(linetype_values))
        override_colour <- rep("black",   length(linetype_values))
      }

      p <- p + ggplot2::guides(
        linetype = ggplot2::guide_legend(
          title        = shape_var,
          override.aes = list(
            fill     = override_fill,
            colour   = override_colour,
            linetype = linetype_values,
            size     = 0.7
          )
        )
      )
    }

    # ---------- BOXPLOT ----------
  } else if (geom_type == "boxplot") {

    x_var <- color_var
    if (is.null(x_var))
      stop("Boxplot requires a valid `color_by` aesthetic.")

    aes_box <- ggplot2::aes(
      x = factor(.data[[x_var]], levels = unique(.data[[x_var]])),
      y = .data[[var_col]]
    )

    if (!is.null(color_var)) {
      aes_box$fill   <- rlang::sym(color_var)
      aes_box$colour <- rlang::sym(color_var)
    }

    if (!is.null(shape_var))
      aes_box$linetype <- rlang::sym(shape_var)

    p <- ggplot2::ggplot(df, aes_box) +
      ggplot2::geom_boxplot(
        alpha         = 0.4,
        linewidth     = lw_val,
        outlier.shape = 21,
        outlier.size  = 1.4
      ) +
      base$plot$theme

    if (!is.null(color_var)) {
      p <- p + ggplot2::scale_colour_manual(values = palette_values)
      p <- p + ggplot2::scale_fill_manual(values = fill_palette)
    }

    if (!is.null(shape_var)) {
      p <- p + ggplot2::scale_linetype_manual(values = linetype_values)
    }

    # dataset legend override if shape active
    if (!is.null(shape_var) &&
        dplyr::n_distinct(df[[shape_var]]) > 1) {

      if (!is.null(color_var) && color_var == shape_var) {
        override_fill   <- fill_palette
        override_colour <- palette_values
      } else {
        override_fill   <- rep("grey85", length(linetype_values))
        override_colour <- rep("black",   length(linetype_values))
      }

      p <- p + ggplot2::guides(
        linetype = ggplot2::guide_legend(
          title        = shape_var,
          override.aes = list(
            fill     = override_fill,
            colour   = override_colour,
            linetype = linetype_values,
            size     = 0.7
          )
        )
      )
    }

    p <- p +
      ggplot2::labs(
        title    = paste("Distribution of Delta", tools::toTitleCase(variable)),
        x        = x_var,
        y        = "Value",
        colour   = color_var,
        fill     = color_var,
        linetype = shape_var
      )

    return(p)

  } else {
    stop("`geom_type` must be 'histogram', 'density', or 'boxplot'.")
  }

  # ============================================================
  # 10. Final labels for histogram/density
  # ============================================================
  p <- p +
    ggplot2::scale_x_continuous(labels = scales::label_number()) +
    ggplot2::scale_y_continuous(labels = scales::label_number()) +
    ggplot2::labs(
      title    = paste("Distribution of Delta", tools::toTitleCase(variable)),
      x        = paste("Delta", tools::toTitleCase(variable)),
      y        = "Density",
      colour   = color_var,
      fill     = color_var,
      linetype = shape_var
    )

  return(p)
}
