#' Plot Marginal Distributions of Incremental Outcomes
#'
#' Visualizes marginal distributions of incremental costs
#' (\code{Delta_Cost}) or incremental effects (\code{Delta_Effect}) using
#' bootstrap replicates from a \code{cea_results_list} object generated by
#' \code{compute_icers}. Supported geometries include histogram, density and
#' boxplot. The function adheres to the unified graphical conventions of the
#' CEAgroupR package, including consistent colour mappings, palette assignment,
#' faceting rules, and user-driven aesthetic overrides.
#'
#' Colour aesthetics reflect the primary comparison grouping unless overridden
#' by the user. Fill aesthetics reuse the same palette with controlled
#' transparency. When \code{shape_by = NULL} or \code{"none"}, all linetype and
#' shape aesthetics are disabled. Legends corresponding to aesthetics with a
#' single effective level are automatically suppressed. For histogram
#' geometries, dataset-level legends are rendered using line-based keys to
#' ensure visual informativeness.
#'
#' @inheritParams plot.icers
#'
#' @param variable Character. Either \code{"cost"} (for \code{Delta_Cost}) or
#'   \code{"effect"} (for \code{Delta_Effect}).
#' @param geom_type Character indicating the geometry to use:
#'   \code{"histogram"}, \code{"density"}, or \code{"boxplot"}.
#' @param bins Integer. Number of bins for the histogram geometry.
#'
#' @return A \code{ggplot} object.
#' @rawNamespace export(plot.marginals)
plot.marginals <- function(
    data,
    variable     = "cost",
    geom_type    = "histogram",
    color_by     = NULL,
    shape_by     = NULL,
    facet_by     = NULL,
    mode         = "Overall",
    filter_expr  = NULL,
    facet_scales = "fixed",
    palette      = "Dark2",
    bins         = 30,
    ...
) {

  `%||%` <- function(a, b) if (!is.null(a)) a else b
  alpha_fill <- function(cols) scales::alpha(cols, 0.5)

  # ============================================================
  # 1. Input extraction
  # ============================================================
  if (inherits(data, "cea_results_list")) {

    if (is.null(data$combined_replicates))
      stop("'combined_replicates' not found. Run compute_icers().")

    df <- data$combined_replicates

  } else if (inherits(data, "data.frame")) {

    df <- data

  } else {
    stop("Input must be a `cea_results_list` or a data frame.")
  }

  if (!"group_uid" %in% names(df)) {
    df$group_uid <- with(
      df,
      paste(dataset, subgroup_var, subgroup_level, comparison, sep = "_")
    )
  }

  # ============================================================
  # 2. Optional filtering
  # ============================================================
  if (!is.null(filter_expr)) {
    df <- dplyr::filter(df, !!rlang::parse_expr(filter_expr))
  }

  # ============================================================
  # 3. Mode filtering
  # ============================================================
  mode <- match.arg(mode, c("Overall", "Subgroups"))

  if (mode == "Overall") {
    df <- df[df$subgroup_var == "Overall" | is.na(df$subgroup_var), ]
  } else {
    df <- df[df$subgroup_var != "Overall" & !is.na(df$subgroup_var), ]
  }

  # ============================================================
  # 4. Delta variable selection
  # ============================================================
  var_col <- switch(
    variable,
    "cost"   = "Delta_Cost",
    "effect" = "Delta_Effect",
    stop("`variable` must be 'cost' or 'effect'.")
  )

  # ============================================================
  # 5. Defaults and user overrides
  # ============================================================
  default_color <- "comparison"
  default_shape <- "dataset"
  default_facet <- if (mode == "Subgroups") "subgroup" else "none"

  resolved_color <- color_by %||% default_color
  resolved_shape <- shape_by %||% default_shape
  resolved_facet <- facet_by %||% default_facet

  if (identical(color_by, "none")) resolved_color <- NULL
  if (identical(shape_by, "none")) resolved_shape <- NULL
  if (identical(facet_by, "none")) resolved_facet <- NULL

  # ============================================================
  # 6. Base plot engine
  # ============================================================
  base <- ce_plot_base(
    data         = df,
    color_by     = resolved_color,
    shape_by     = resolved_shape,
    facet_by     = resolved_facet,
    facet_scales = facet_scales,
    palette      = palette
  )

  p               <- base$plot
  color_var       <- base$color_var
  shape_var       <- base$shape_var
  palette_values  <- base$palette_values
  linetype_values <- base$linetype_values
  shape_values    <- base$shape_values
  fill_palette    <- alpha_fill(palette_values)

  args      <- list(...)
  alpha_val <- args$alpha     %||% 0.5
  lw_val    <- args$linewidth %||% 0.6

  # ============================================================
  # 7. Scales for colour and fill
  # ============================================================
  if (!is.null(color_var)) {
    p <- p + ggplot2::scale_colour_manual(values = palette_values)
    p <- p + ggplot2::scale_fill_manual(values = fill_palette)
  }

  # ============================================================
  # 8. Shape and linetype scales (only if active)
  # ============================================================
  shape_active <- !is.null(shape_var)

  if (shape_active) {
    p <- p + ggplot2::scale_linetype_manual(values = linetype_values)
    p <- p + ggplot2::scale_shape_manual(values = shape_values)
  } else {
    p <- p + ggplot2::guides(linetype = "none", shape = "none")
  }

  # ============================================================
  # 8b. Legend cleanup (automatic suppression of non-informative legends)
  # ============================================================
  if (!is.null(color_var) &&
      dplyr::n_distinct(df[[color_var]]) == 1) {
    p <- p + ggplot2::guides(
      colour = "none",
      fill   = "none"
    )
  }

  if (shape_active &&
      dplyr::n_distinct(df[[shape_var]]) == 1) {
    p <- p + ggplot2::guides(
      shape    = "none",
      linetype = "none"
    )
  }

  # ============================================================
  # 9. Geometry layers
  # ============================================================

  # ------------------------------ DENSITY ------------------------------
  if (geom_type == "density") {

    aes_density <- ggplot2::aes(
      x = .data[[var_col]],
      group = group_uid
    )

    if (!is.null(color_var)) {
      aes_density$colour <- rlang::sym(color_var)
      aes_density$fill   <- rlang::sym(color_var)
    }

    if (shape_active)
      aes_density$linetype <- rlang::sym(shape_var)

    p <- p + ggplot2::geom_density(
      data        = df,
      mapping     = aes_density,
      alpha       = alpha_val,
      linewidth   = lw_val,
      inherit.aes = FALSE
    )

    # ------------------------------ HISTOGRAM ------------------------------
  } else if (geom_type == "histogram") {

    aes_hist <- ggplot2::aes(
      x = .data[[var_col]],
      group = group_uid
    )

    if (!is.null(color_var)) {
      aes_hist$fill   <- rlang::sym(color_var)
      aes_hist$colour <- rlang::sym(color_var)
    }

    if (shape_active)
      aes_hist$linetype <- rlang::sym(shape_var)

    p <- p + ggplot2::geom_histogram(
      data        = df,
      mapping     = aes_hist,
      bins        = bins,
      alpha       = alpha_val,
      linewidth   = lw_val,
      position    = "identity",
      inherit.aes = FALSE
    )

    if (shape_active &&
        dplyr::n_distinct(df[[shape_var]]) > 1) {

      p <- p + ggplot2::guides(
        linetype = ggplot2::guide_legend(
          title        = shape_var,
          override.aes = list(
            colour    = "black",
            fill      = NA,
            linetype  = linetype_values,
            linewidth = 0.8
          )
        )
      )
    }

    # ------------------------------ BOX PLOT ------------------------------
  } else if (geom_type == "boxplot") {

    x_var <- color_var
    if (is.null(x_var))
      stop("Boxplot requires a valid `color_by` aesthetic.")

    aes_box <- ggplot2::aes(
      x = .data[[x_var]],
      y = .data[[var_col]]
    )

    if (!is.null(color_var)) {
      aes_box$fill   <- rlang::sym(color_var)
      aes_box$colour <- rlang::sym(color_var)
    }

    if (shape_active)
      aes_box$linetype <- rlang::sym(shape_var)

    p <- p + ggplot2::geom_boxplot(
      data          = df,
      mapping       = aes_box,
      alpha         = alpha_val,
      linewidth     = lw_val,
      outlier.shape = 21,
      outlier.size  = 1.4,
      inherit.aes   = FALSE
    )
  }

  # ============================================================
  # 10. Final labels and scales
  # ============================================================
  if (geom_type != "boxplot") {

    p <- p +
      ggplot2::scale_x_continuous(labels = scales::label_number()) +
      ggplot2::scale_y_continuous(labels = scales::label_number()) +
      ggplot2::labs(
        title    = paste("Distribution of Delta", tools::toTitleCase(variable)),
        x        = paste("Delta", tools::toTitleCase(variable)),
        y        = "Density",
        colour   = color_var,
        fill     = color_var,
        linetype = shape_var
      )

  } else {

    p <- p +
      ggplot2::scale_y_continuous(labels = scales::label_number()) +
      ggplot2::labs(
        title    = paste("Distribution of Delta", tools::toTitleCase(variable)),
        x        = color_var,
        y        = "Value",
        colour   = color_var,
        fill     = color_var,
        linetype = shape_var
      )
  }

  return(p)
}
