#' Plot incremental cost-effectiveness results (ICER plane)
#'
#' Produces a cost-effectiveness plane using bootstrap replicates from one or
#' several analyses. Supports multiple visualization modes for overall and
#' subgroup analyses. Optionally displays mean markers and a single 2D-density
#' contour (default 95%) around each group of points.
#'
#' @param data A tibble generated by \code{\link{combine_icers_results}}.
#' @param mode Character. Visualization mode: "overall", "subgroups",
#'   "bylevels", or "bygroup".
#' @param subgroups Optional character vector specifying which subgroup
#'   variables to include (for modes other than "overall").
#' @param lambda Numeric. Willingness-to-pay threshold (optional).
#' @param facet Logical. If TRUE, facet the plot according to \code{facet_by}.
#' @param facet_by Character. For mode = "subgroups", determines the faceting
#'   scheme: "vars" (facet by subgroup variable) or "levels" (facet by subgroup level).
#' @param alpha Numeric transparency for points (default = 0.5).
#' @param size Numeric point size (default = 1).
#' @param show_means Logical. If TRUE, add a cross at the mean of each group.
#' @param show_contours Logical. If TRUE, add a 2D density contour around each group.
#' @param contour_level Numeric. Probability level for the contour (default = 0.95).
#' @param palette Character. Color palette name from RColorBrewer (default = "Set2").
#'
#' @return A ggplot object representing the cost-effectiveness plane.
#'
#' @importFrom ggplot2 ggplot aes geom_point geom_hline geom_vline geom_abline
#'   facet_wrap labs theme_bw geom_contour scale_color_brewer
#' @importFrom dplyr filter group_by summarise group_split
#' @importFrom MASS kde2d
#' @export
plot.icers <- function(data,
                       mode = "overall",
                       subgroups = NULL,
                       lambda = NULL,
                       facet = FALSE,
                       facet_by = "vars",
                       alpha = 0.5,
                       size = 1,
                       show_means = TRUE,
                       show_contours = TRUE,
                       contour_level = 0.95,
                       palette = "Set2") {

  required_cols <- c("Delta_Cost", "Delta_Effect", "level", "subgroup", "source")
  missing_cols <- setdiff(required_cols, names(data))
  if (length(missing_cols) > 0) {
    stop("Missing required columns in 'data': ", paste(missing_cols, collapse = ", "))
  }

  valid_modes <- c("overall", "subgroups", "bylevels", "bygroup")
  if (!mode %in% valid_modes) {
    stop("Invalid mode. Choose one of: ", paste(valid_modes, collapse = ", "))
  }

  # Filter data
  if (mode == "overall") {
    df <- dplyr::filter(data, level == "Overall")
  } else {
    if (is.null(subgroups)) stop("Argument 'subgroups' must be provided for this mode.")
    df <- dplyr::filter(data, level %in% subgroups)
  }

  # Base plot
  p <- ggplot2::ggplot(df, ggplot2::aes(x = Delta_Effect, y = Delta_Cost)) +
    ggplot2::geom_hline(yintercept = 0, color = "gray60", linetype = "dashed") +
    ggplot2::geom_vline(xintercept = 0, color = "gray60", linetype = "dashed") +
    ggplot2::theme_bw() +
    ggplot2::labs(
      x = expression(Delta * " Effect"),
      y = expression(Delta * " Cost"),
      title = "Cost-effectiveness plane"
    )

  if (!is.null(lambda)) {
    p <- p + ggplot2::geom_abline(
      slope = lambda, intercept = 0, color = "red", size = 0.6
    )
  }

  # -------------------------------------------------------------------------
  # Mode: overall
  # -------------------------------------------------------------------------
  if (mode == "overall") {

    p <- p + ggplot2::geom_point(color = "steelblue", alpha = alpha, size = size)

    if (show_means) {
      mean_df <- data.frame(
        Delta_Effect = mean(df$Delta_Effect, na.rm = TRUE),
        Delta_Cost = mean(df$Delta_Cost, na.rm = TRUE)
      )
      p <- p + ggplot2::geom_point(
        data = mean_df,
        ggplot2::aes(x = Delta_Effect, y = Delta_Cost),
        shape = 4, color = "steelblue", size = 3, stroke = 1.2
      )
    }

    if (show_contours) {
      dens <- MASS::kde2d(df$Delta_Effect, df$Delta_Cost, n = 150)
      cutoff <- quantile(as.vector(dens$z), probs = contour_level, na.rm = TRUE)
      d <- data.frame(expand.grid(x = dens$x, y = dens$y), z = as.vector(dens$z))
      p <- p + ggplot2::geom_contour(
        data = d, ggplot2::aes(x = x, y = y, z = z),
        breaks = cutoff, color = "steelblue", alpha = alpha + 0.2
      )
    }

    return(p)
  }

  # -------------------------------------------------------------------------
  # Mode: subgroups
  # -------------------------------------------------------------------------
  if (mode == "subgroups") {

    # Facet by variable: 2 colors (yes/no)
    if (facet && facet_by == "vars") {

      p <- ggplot2::ggplot(df, ggplot2::aes(
        x = Delta_Effect, y = Delta_Cost, color = subgroup
      )) +
        ggplot2::geom_hline(yintercept = 0, color = "gray60", linetype = "dashed") +
        ggplot2::geom_vline(xintercept = 0, color = "gray60", linetype = "dashed") +
        ggplot2::theme_bw() +
        ggplot2::facet_wrap(~ level) +
        ggplot2::scale_color_brewer(palette = palette) +
        ggplot2::labs(color = "Subgroup level",
                      x = expression(Delta * " Effect"),
                      y = expression(Delta * " Cost"),
                      title = "Cost-effectiveness plane") +
        ggplot2::geom_point(alpha = alpha, size = size)

      # Mean crosses
      if (show_means) {
        mean_df <- df |>
          dplyr::group_by(level, subgroup) |>
          dplyr::summarise(
            Delta_Effect = mean(Delta_Effect, na.rm = TRUE),
            Delta_Cost = mean(Delta_Cost, na.rm = TRUE),
            .groups = "drop"
          )
        p <- p + ggplot2::geom_point(
          data = mean_df,
          ggplot2::aes(x = Delta_Effect, y = Delta_Cost, color = subgroup),
          shape = 4, size = 3, stroke = 1.2
        )
      }

      # Contours per subgroup and variable (facet-aware)
      if (show_contours) {
        contour_list <- df |>
          dplyr::group_split(level, subgroup)

        contour_df <- do.call(rbind, lapply(contour_list, function(g) {
          if (nrow(g) < 15) return(NULL)
          dens <- MASS::kde2d(g$Delta_Effect, g$Delta_Cost, n = 150)
          cutoff <- quantile(as.vector(dens$z), probs = contour_level, na.rm = TRUE)
          data.frame(
            expand.grid(x = dens$x, y = dens$y),
            z = as.vector(dens$z),
            level = unique(g$level),
            subgroup = unique(g$subgroup),
            cutoff = cutoff
          )
        }))

        if (!is.null(contour_df)) {
          p <- p + ggplot2::geom_contour(
            data = contour_df,
            ggplot2::aes(x = x, y = y, z = z, color = subgroup,
                         group = interaction(level, subgroup)),
            breaks = unique(contour_df$cutoff),
            alpha = alpha + 0.2,
            inherit.aes = FALSE
          )
        }
      }

      return(p)
    }

    # Facet by level: 2 colors (variables)
    if (facet && facet_by == "levels") {

      p <- ggplot2::ggplot(df, ggplot2::aes(
        x = Delta_Effect, y = Delta_Cost, color = level
      )) +
        ggplot2::geom_hline(yintercept = 0, color = "gray60", linetype = "dashed") +
        ggplot2::geom_vline(xintercept = 0, color = "gray60", linetype = "dashed") +
        ggplot2::theme_bw() +
        ggplot2::facet_wrap(~ subgroup) +
        ggplot2::scale_color_brewer(palette = palette) +
        ggplot2::labs(color = "Subgroup variable",
                      x = expression(Delta * " Effect"),
                      y = expression(Delta * " Cost"),
                      title = "Cost-effectiveness plane") +
        ggplot2::geom_point(alpha = alpha, size = size)

      # Mean crosses
      if (show_means) {
        mean_df <- df |>
          dplyr::group_by(level, subgroup) |>
          dplyr::summarise(
            Delta_Effect = mean(Delta_Effect, na.rm = TRUE),
            Delta_Cost = mean(Delta_Cost, na.rm = TRUE),
            .groups = "drop"
          )
        p <- p + ggplot2::geom_point(
          data = mean_df,
          ggplot2::aes(x = Delta_Effect, y = Delta_Cost, color = level),
          shape = 4, size = 3, stroke = 1.2
        )
      }

      # Contours facet-aware
      if (show_contours) {
        contour_list <- df |>
          dplyr::group_split(level, subgroup)

        contour_df <- do.call(rbind, lapply(contour_list, function(g) {
          if (nrow(g) < 15) return(NULL)
          dens <- MASS::kde2d(g$Delta_Effect, g$Delta_Cost, n = 150)
          cutoff <- quantile(as.vector(dens$z), probs = contour_level, na.rm = TRUE)
          data.frame(
            expand.grid(x = dens$x, y = dens$y),
            z = as.vector(dens$z),
            level = unique(g$level),
            subgroup = unique(g$subgroup),
            cutoff = cutoff
          )
        }))

        if (!is.null(contour_df)) {
          p <- p + ggplot2::geom_contour(
            data = contour_df,
            ggplot2::aes(x = x, y = y, z = z, color = level,
                         group = interaction(level, subgroup)),
            breaks = unique(contour_df$cutoff),
            alpha = alpha + 0.2,
            inherit.aes = FALSE
          )
        }
      }

      return(p)
    }
  }

  return(p)
}
